name: Auto-merge PDF-only PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Check changed files are all PDFs
        id: check
        run: |
          git fetch origin ${{ github.base_ref }}
          changed=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "Changed files: $changed"
          if echo "$changed" | grep -vE '\.pdf$'; then
            echo "Non-PDF files detected. Skipping merge."
            echo "result=fail" >> $GITHUB_OUTPUT
          else
            echo "Only PDF files detected. Safe to merge."
            echo "result=pass" >> $GITHUB_OUTPUT
          fi

      - name: Auto-merge PDF PR
        if: steps.check.outputs.result == 'pass'
        run: |
          gh pr merge ${{ github.event.pull_request.html_url }} --squash --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
